name=20160726_QuAASI_ATM
${name}.pdf: ${name}.tex beamerthemedlr.sty beamercolorthemedlr.sty beamerinnerthemedlr.sty beamerouterthemedlr.sty
	pdflatex ${name}.tex
clean:
	rm -f *.out *.aux *.log *.bak *.backup *.toc *~ *.ps *.dvi *.bbl *.blg *.idx *.ilg *.ind *.fls *.snm *.nav
